
package sg.vista.admin;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import sg.dao.emergencia.DAOEmergenciaArchivo;
import sg.dao.usuario.DAOUsuarioArchivo;
import sg.modelo.Emergencia;
import sg.modelo.EntidadDeRiesgo;
import sg.modelo.GestionEmergencia;
import sg.modelo.Usuario;
import sg.vista.Inicio;

/**
 *
 * @author Luz Torres
 */
public class PrincipalAdmin extends javax.swing.JFrame {
    GestionEmergencia gest = GestionEmergencia.getInstancia();
    Inicio ini;
    
    /**
     * Creates new form PrincipalAdmin
     */
    public PrincipalAdmin(Inicio ini) {
        initComponents();
        this.ini = ini;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarXEntidad = new javax.swing.JButton();
        buscarXZona = new javax.swing.JButton();
        buscarXEmergencia = new javax.swing.JButton();
        porcentajeXTipo = new javax.swing.JButton();
        porcentajeAtendidas = new javax.swing.JButton();
        buscarXUsuario = new javax.swing.JButton();
        todosLosUsuarios = new javax.swing.JButton();
        todasLasEmergencias = new javax.swing.JButton();
        todasLasEntidades = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        buscarXEntidad.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        buscarXEntidad.setText("BUSCAR POR ENTIDAD");
        buscarXEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarXEntidadActionPerformed(evt);
            }
        });

        buscarXZona.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        buscarXZona.setText("BUSCAR POR ZONA");
        buscarXZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarXZonaActionPerformed(evt);
            }
        });

        buscarXEmergencia.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        buscarXEmergencia.setText("BUSCAR POR EMERGENCIA");
        buscarXEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarXEmergenciaActionPerformed(evt);
            }
        });

        porcentajeXTipo.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        porcentajeXTipo.setText("PORCENTAJE TIPO DE EMERGENCIA");
        porcentajeXTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeXTipoActionPerformed(evt);
            }
        });

        porcentajeAtendidas.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        porcentajeAtendidas.setText("PORCENTAJE ATENDIDAS");
        porcentajeAtendidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        porcentajeAtendidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porcentajeAtendidasActionPerformed(evt);
            }
        });

        buscarXUsuario.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        buscarXUsuario.setText("BUSCAR POR USUARIO");
        buscarXUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarXUsuarioActionPerformed(evt);
            }
        });

        todosLosUsuarios.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        todosLosUsuarios.setText("VER TODOS LOS USUARIOS");
        todosLosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todosLosUsuariosActionPerformed(evt);
            }
        });

        todasLasEmergencias.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        todasLasEmergencias.setText("VER TODAS LAS EMERGENCIAS");
        todasLasEmergencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todasLasEmergenciasActionPerformed(evt);
            }
        });

        todasLasEntidades.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        todasLasEntidades.setText("VER TODAS LAS ENTIDADES");
        todasLasEntidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todasLasEntidadesActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(todasLasEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(todosLosUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(porcentajeAtendidas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarXEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(porcentajeXTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarXUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarXZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(todasLasEmergencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(buscarXEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(295, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(buscarXUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarXEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarXZona, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcentajeAtendidas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porcentajeXTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(todosLosUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(todasLasEmergencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(todasLasEntidades, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(buscarXEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(387, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarXEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarXEntidadActionPerformed
        String entidad = JOptionPane.showInputDialog("Ingrese el nombre de la entidad: ");
        JOptionPane.showMessageDialog(null, gest.listarXEntidad(entidad));
    }//GEN-LAST:event_buscarXEntidadActionPerformed

    private void buscarXZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarXZonaActionPerformed
        String zona = JOptionPane.showInputDialog("Ingrese la zona: ");
        JOptionPane.showMessageDialog(null, gest.listarXZona(zona));
    }//GEN-LAST:event_buscarXZonaActionPerformed

    private void buscarXEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarXEmergenciaActionPerformed
        String emergencia = JOptionPane.showInputDialog("Ingrese el tipo de emergencia: ");
        JOptionPane.showMessageDialog(null, gest.listarXEmergencia(emergencia));
    }//GEN-LAST:event_buscarXEmergenciaActionPerformed

    private void buscarXUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarXUsuarioActionPerformed
        String usuario = JOptionPane.showInputDialog("Ingrese el nombre del usuario: ");
        JOptionPane.showMessageDialog(null, gest.listarXUsuario(usuario));
    }//GEN-LAST:event_buscarXUsuarioActionPerformed

    private void todosLosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todosLosUsuariosActionPerformed
        DAOUsuarioArchivo dao = new DAOUsuarioArchivo();
        List<Usuario> lista = dao.listar();
        
        String[] columnas = {"Nombre", "Cedula", "Zona", "Ubicacion"};
        Object[][] filas = new Object[lista.size()][4];
        
        for (int i = 0; i < lista.size(); i++) {
            Usuario usuario = lista.get(i);
            filas[i][0] = usuario.getNombre();
            filas[i][1] = usuario.getCedula();
            filas[i][2] = usuario.getZona();
            filas[i][3] = usuario.getUbicacion();
        }
        
        JTable tablita = new JTable(filas, columnas);
        JScrollPane scroll = new JScrollPane(tablita);
        scroll.setPreferredSize(new Dimension(800, 300));
        
        JOptionPane.showMessageDialog(null, scroll, "Listado de usuarios", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_todosLosUsuariosActionPerformed

    private void porcentajeXTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeXTipoActionPerformed
        String tipo = JOptionPane.showInputDialog("Ingrese el tipo de emergencia");
        JOptionPane.showMessageDialog(null, gest.porcenXTipoEmergencia(tipo));
    }//GEN-LAST:event_porcentajeXTipoActionPerformed

    private void porcentajeAtendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porcentajeAtendidasActionPerformed
        String entidad = JOptionPane.showInputDialog("Ingrese el nombre de la entidad: ");
        JOptionPane.showMessageDialog(null, gest.porcenEmergAtendXEntidad(entidad));
    }//GEN-LAST:event_porcentajeAtendidasActionPerformed

    private void todasLasEmergenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todasLasEmergenciasActionPerformed
        DAOEmergenciaArchivo dao = new DAOEmergenciaArchivo();
        List<Emergencia> lista = dao.listar();
        String[] columnas = {"ID", "Tipo", "Casua", "Fecha", "Zona", "Severidad"};
        Object[][] filas = new Object[lista.size()][6];
        
        for (int i = 0; i < lista.size(); i++) {
            Emergencia emerg = lista.get(i);
            filas[i][0] = emerg.getId();
            filas[i][1] = emerg.getTipo();
            filas[i][2] = emerg.getCausa();
            filas[i][3] = emerg.getFecha();
            filas[i][4] = emerg.getZonas();
            filas[i][5] = emerg.getSeveridad();
        }
        
        JTable tablita = new JTable(filas, columnas);
        JScrollPane scroll = new JScrollPane(tablita);
        scroll.setPreferredSize(new Dimension(980, 300));
        
        JOptionPane.showMessageDialog(null, scroll, "Listado de emergencias", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_todasLasEmergenciasActionPerformed

    private void todasLasEntidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todasLasEntidadesActionPerformed
        List<EntidadDeRiesgo> lista = gest.getEntidades();
        String[] columnas = {"ID", "Nombre", "Estado", "Tipo emergencia", "Cant atendidas"};
        Object[][] filas = new Object[lista.size()][5];
        
        for (int i = 0; i < lista.size(); i++) {
            EntidadDeRiesgo entidad = lista.get(i);
            filas[i][0] = entidad.getId();
            filas[i][1] = entidad.getNombre();
            filas[i][2] = entidad.isDisponible()? "Disponible" : "No disponible";
            filas[i][3] = entidad.getEmergenciaQueAtiende();
            filas[i][4] = entidad.getCantEmergAtendidas();
        }
        
        JTable tablita = new JTable(filas, columnas);
        JScrollPane scroll = new JScrollPane(tablita);
        scroll.setPreferredSize(new Dimension(600, 300));
        
        JOptionPane.showMessageDialog(null, scroll, "Listado de entidades", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_todasLasEntidadesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new PrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarXEmergencia;
    private javax.swing.JButton buscarXEntidad;
    private javax.swing.JButton buscarXUsuario;
    private javax.swing.JButton buscarXZona;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton porcentajeAtendidas;
    private javax.swing.JButton porcentajeXTipo;
    private javax.swing.JButton todasLasEmergencias;
    private javax.swing.JButton todasLasEntidades;
    private javax.swing.JButton todosLosUsuarios;
    // End of variables declaration//GEN-END:variables
}
